version: '3.8'
services:
  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: Sakshi
      MYSQL_DATABASE: user_db
      MYSQL_USER: Sakshi
      MYSQL_PASSWORD: Sakshi
    ports:
      - "3306:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - foodapp

  mysql-restaurant-order:
    image: mysql:8.0
    container_name: mysql-restaurant-order
    environment:
      MYSQL_ROOT_PASSWORD: Sakshi
      MYSQL_DATABASE: restaurant_order_db
      MYSQL_USER: Sakshi
      MYSQL_PASSWORD: Sakshi
    ports:
      - "3307:3306"
    volumes:
      - mysql-restaurant-order-data:/var/lib/mysql
    networks:
      - foodapp

  mysql-payment-delivery:
    image: mysql:8.0
    container_name: mysql-payment-delivery
    environment:
      MYSQL_ROOT_PASSWORD: Sakshi
      MYSQL_DATABASE: payment_delivery_db
      MYSQL_USER: Sakshi
      MYSQL_PASSWORD: Sakshi
    ports:
      - "3308:3306"
    volumes:
      - mysql-payment-delivery-data:/var/lib/mysql
    networks:
      - foodapp

volumes:
  mysql-user-data:
  mysql-restaurant-order-data:
  mysql-payment-delivery-data:

networks:
  foodapp:
    driver: bridge

