spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://grabobite.netlify.app"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: https://user-service-6eg1.onrender.com
          predicates:
            - Path=/auth/**

        - id: restaurant-service
          uri: https://restaurant-service-x7ei.onrender.com
          predicates:
            - Path=/api/restaurants/**
            
#        - id: order-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/orders/**
#
#        - id: payment-service
#          uri: http://localhost:8084
#          predicates:
#            - Path=/payments/**
#
#        - id: delivery-service
#          uri: http://localhost:8086
#          predicates:
#            - Path=/deliveries/**
#
#        - id: notification-service
#          uri: http://localhost:8085
#          predicates:
#            - Path=/notifications/**
