spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /users/**

        - id: RESTAURANT-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/restaurants/**

        - id: ORDER-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**

        - id: PAYMENT-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**

        - id: DELIVERY-SERVICE
          uri: http://localhost:8086
          predicates:
            - Path=/deliveries/**

        - id: NOTIFICATION-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**
  application:
    name: API_GATEWAY